name: 'auto-release'
author: 'sqaisar'
description: 'AutoRelease with Semantic Versioning from next and latest branches'
branding:
  icon: activity
  color: green
inputs:
  github-token: # id of input
    default: ${{ github.token }}
    required: false
    description: 'the GH token to connect to github from the action'
  slack-token:
    description: "Slack token to send release notes to slack"
    required: true
  slack-channels:
    description: "Slack channels to send release notes to, pass multiple , separated values e.g channel1, channel2"
    required: true
  notify-on-pre-release:
    description: "Weather to notify on pre-release"
    required: false
    default: "true"
  dry-run:
    description: "check if the action would succeed"
    required: false
    default: "FALSE"
  release-branch:
    description: "release branch name"
    required: false
    default: "release"
  main-branch:
    description: "main branch name"
    required: false
    default: "next"
outputs:
  new-tag: # id of output
    description: 'new tag'
  tag: # id of output
    description: 'latest tag'
runs:
  using: 'node16'
  main: 'dist/index.js'
